### ISSUE TITLE
Possible incompatibility with Create

### ISSUE THREAD

**Issue by mxKeaton** [Kikugie/elytra-trims#29]
### Bug description

Whenever I add this mod minecraft won't launch anymore and it gives me a mixin error
It mentiones "OpenCreateMenuButton", that is why I assume the possible conflicts

### Steps to reproduce

1. Have Create installed
2. Add Elytra Trims
3. Crashes on Startup

### Expected behavior

not crash

### Relevant logs

net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4710()" because "$$6" is null
	at net.minecraft.class_918.method_4019(class_918.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51425(class_332.java:518) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51424(class_332.java:511) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51427(class_332.java:491) ~[client-intermediary.jar:?]
	at com.simibubi.create.infrastructure.gui.OpenCreateMenuButton.method_48589(OpenCreateMenuButton.java:34) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_4264.method_48579(class_4264.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25394(class_442.java:289) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 9 more

### Minecraft version

1.20.1

### Elytra Trims version

1.2.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
You're using an old version of Elytra Trims. This shouldn't be a problem with 1.3.3

**Comment by mxKeaton** [comment]
Ah no my bad. Was just rushing out this issue and copied the default version because I assumed it is the most recent one. The issue occurs on version 1.3.3

**Comment by kikugie** [comment]
This doesn't look like a direct incompatibility with Create: 
![2023-09-17_08 32 06](https://github.com/kikugie/elytra-trims/assets/50152507/05069398-fbe1-4a3c-b435-dae1567ca153)

Can you upload the full game log to https://mclo.gs? It includes the mod list and other non-crashing errors that can be useful

**Comment by mxKeaton** [comment]
The create issue seems to be connected to something else yeah.
Still, after adding Elytra Trims to the pack it can not launch.
https://mclo.gs/1EMLUu4

It just stops at the last line and I need to kill it manually

**Comment by kikugie** [comment]
What modpack is that? I can't realistically check every mod from that list one by one.  
Also Elytra Trims won't work with Customizable Elytra (both have similar features, though Elytra Trims has more).

**Comment by mxKeaton** [comment]
It is a custom pack that I have been building up by myself. Sadly it won't work even after disabling Customizable Elytra. Same goes for all the other Elytra mods.

If I am the only one with this issue then you can try to ignore it. Most likely a conflict with a small mod or even resourcepack

**Comment by Crec0** [comment]
binary search and pin down the culprit

**Comment by Crec0** [comment]
A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.

Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.

Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order.

By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.

**Comment by sirben99** [comment]
Hey!

I've run into the same issue that OP ran into and have been trying to solve it and managed to come to an confusing yet fruitful conclusion.

I found out that if you put 9 mods together, those being:

architectury-9.1.12-fabric: https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/4663009

create-fabric-0.5.1-d-build.1161+mc1.20.1: https://www.curseforge.com/minecraft/mc-mods/create-fabric/files/4721061

doapi-1.2.7-fabric: https://www.curseforge.com/minecraft/mc-mods/do-api/files/4732829

elytratrims-1.3.3+1.20: https://www.curseforge.com/minecraft/mc-mods/elytra-trims/files/4731236

fabric-api-0.90.0+1.20.1: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4787692

letsdo-meadow-fabric-1.3.1 OR letsdo-beachparty-fabric-1.1.2:
https://www.curseforge.com/minecraft/mc-mods/welcome-to-meadow/files/4741261
https://www.curseforge.com/minecraft/mc-mods/beachparty/files?version=1.20.1

moonlight-1.20-2.8.49-fabric: https://www.curseforge.com/minecraft/mc-mods/selene/files/4797951

sleep_tight-1.20-1.1.6-fabric: https://www.curseforge.com/minecraft/mc-mods/sleep-tight/files/4778255

TerraBlender-fabric-1.20.1-3.0.0.169: https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric/files/4647092

Now, here comes the confusing part and why there is a OR next to the two mods: If you take any of these mods out the game will work. If you replace Meadow mod with Beachparty mod or vice versa, the game will crash with the same error.

I have compared the logs with OP from this post, and we have these mods in common:
Architectury
Create
Elytratrims
Fabric-API (Op has lower version,  0.88.1+1.20.1)
Moonlight (Op has lower version, 1.20-2.8.21)
Sleep tight (Op has lower version, 1.20-1.1.3)

My conclusion is that one of these mods is messing with other mods in unexpected way and making the game crash on launch if put together. I cant say what is really crashing OP:s game, since the crash seems to be caused by a different mod combination.

Log: https://mclo.gs/5GCkK2j

Crash report: https://mclo.gs/O8tSELz

I hope this helps solve the issue somehow!
